[package]
name = "rsa-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.0"
hex = "0.4.0"
rsa = "0.6.0"
rand = "0.8"
rand_chacha = "0.3"